[dependencies]

[package]
  cjc-version = "1.0.1"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "derive_builder"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "2.0.1"
  package-configuration = {}
